# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81e7eacc51f6441b8b3118a0d2b1629dfef536b81fc247bbb2bdc9f56e1dca82d1d2904bf1f3210efda47e46d39576a9199e2451c473672a370bbedce1fd7b0

test:
  secret_key_base: d99e959e1f04fea368843ec4c676765abd06af4143be55871dd2b2f882fedd261c0a47eafb93ed4525844e505703fc91612af0be027e83fbdbfa3a124f6414b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
