# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 147997c5b79842238edaed936a377fd0c4cec0e89dc5458c0478f87d5fa084d8a6b5677a3eed9fe8f1815ee3738f9f14708629243f23886626ff2e2d38f82766

test:
  secret_key_base: c68a40988cac735c0a9c5af4c4df7ea9121a552942ec1c5a1740b9e202a540162f0266715679078ed63d3a85c1dcc3c097b1c81cb723bf82832618ea9321ba73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
